"""add summary to documents

Revision ID: 0475a403acc6
Revises: b6ba80b7124f
Create Date: 2026-09-11 22:05:11.979829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0475a403acc6'
down_revision: Union[str, Sequence[str], None] = 'b6ba80b7124f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
